#!/bin/bash
#supervisorctl start publisher zmq_device display
#curl -X POST http://localhost:6000/registerPath -H "Content-Type: application/json" -d "{\"LoggingPath\":[\"/harness/crs/crs.log\"]}"
#sleep 1
supervisorctl restart crs
sleep 1
supervisorctl restart irm-nova
supervisorctl restart irm-shepard

exit 0

