#!/bin/bash
#!/bin/bash
CONFIG_VARIABLES="main_TENANT_NAME
                  main_USERNAME
                  main_PASSWORD
                  main_NOVA_ENDPOINT
                  network_NET_ID
                  network_IP_TYPE
                  network_UUID
                  overcommit_CPU_RATIO
                  overcommit_MEM_RATIO
                  overcommit_DISK_RATIO"

# configuring irm-nova and irm-neutron
for varname in ${CONFIG_VARIABLES}; do
    value=$(eval "echo \${$varname}")
    if [ -n "$value" ]; then
        read section key <<< "${varname/_/ }"
        sed -i -e"/^\[${section}\]/,/^\[.*\]/{/^${key}:.*/d}" -e"/^\[${section}\]/a${key}: ${value}" /harness/cfg/irm-nova.cfg
        sed -i -e"/^\[${section}\]/,/^\[.*\]/{/^${key}:.*/d}" -e"/^\[${section}\]/a${key}: ${value}" /harness/cfg/irm-neutron.cfg
    fi
done


supervisord -n -c supervisord.conf 
